name: Lunar Tides AweWaken
favicon: null
layout_spectrum: 0.3849086659029126
typography_spectrum: 0.928172369254753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8599221764598042
  lightness: 0.41566061810590327
  saturation: 0.3955176642630249
  rhythmicContrast: 0.12021285155788064
purpose: []
