name: Lunar Tides AweWaken
favicon: null
layout_spectrum: 0.53403
typography_spectrum: 0.08947
title: 'Awakening to Self Love '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.75
  lightness: 0.41566061810590327
  saturation: 0.375
  rhythmicContrast: 0.12021285155788064
purpose: []
