name: Lunar Tides AweWaken
favicon: null
layout_spectrum: 0.53403
typography_spectrum: 0.08947
title: 'Awakening to Self Love '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000f00'
    - '#f8e1c2'
    - '#725979'
    - '#2a3249'
    - '#e78b8c'
  brandStrength: 0.75
  lightness: 0.41566061810590327
  saturation: 0.375
  rhythmicContrast: 0.12021285155788064
purpose: []
